### ISSUE TITLE
Allow 404 to trigger deletion as well as 410

### ISSUE THREAD

**Issue by azaroth42** [w3c-social/webmention#6]
In the Updating section, 410 is explicitly called out as triggering a deletion. It seems like many situations would result in a 404 to trigger deletion as well, such as the domain name being sold and reused, the content management system changing and becoming unaware of all previous URLs, and so forth.

Equally, simply don't refer to HTTP status codes, as one assumes that the 410 would not mention the target, and hence fall under the second clause that triggers deletion :smile_cat:

**Comment by aaronpk** [comment]
Thanks for bringing this up. There has actually been quite a lot of previous discussion on this, however nobody has yet mentioned the points you brought up. Here is some of the past discussion: http://indiewebcamp.com/deleted-404-discussion

All that said, my inclination is that the risks of treating 404 as a delete outweigh the benefits. Happy to continue the discussion on this though.

**Comment by tantek** [comment]
A 410 indicates an explicit deletion. The many situations you mention are not explicit deletions, accidental at best:
* domain name being sold - the original owner did not explicitly delete the previous posts
* domain name being reused - same.

OTOH - the downside risk of temporary 404s due to unreliability in the web causing errant deletions is a real risk and avoiding that greatly outweighs the convenience implied by the "domain name being sold and reused" scenario.
* domain name being sold - might have been hijacked, best not to make that automatically cause individual permalink deletions
* domain name being reused - easy configuration error on the part of the owner, again, better to be forgiving and not cause individual permalink deletions.

**Comment by azaroth42** [comment]
Thanks for the pointer! Then my suggestion would be to double down on 410, and delete the second clause of the source resource no longer linking. All of the same situations would apply to a new resource that happens to be at http://example.com/index.html, post domain transfer or new CMS install. Currently it seems inconsistent, as the 404 response won't link to the target (barring extreme hacking or extreme bad/good luck).

**Comment by aaronpk** [comment]
Interesting point, but I think I would rather be more explicit about when the source no longer links to target triggering a delete. How about this? https://indiewebcamp.com/wiki/index.php?title=Webmention&diff=23495&oldid=23494

**Comment by azaroth42** [comment]
Definitely an improvement :+1: It now defines when deletes should occur consistently with the intent from the linked discussuon, as far as I can tell. It doesn't make any requirements about what to do or not to do for 404s or other scenarios beyond 200 and 410, which I think is fine -- only specify what is necessary to specify :smile_cat:

**Comment by aaronpk** [comment]
Great!
